export const KENPACHI_QUOTES = [
  "POWER ISN'T DETERMINED BY YOUR SIZE. — LOG EVERYTHING.",
  "I NEVER NEEDED EYES TO FIGHT. I NEED DATA.",
  "FIND ME A WARRIOR WHO TRACKS THEIR MACROS.",
  "EVEN CAPTAINS COUNT CALORIES.",
  "THE ONLY MERCY I SHOW IS AN ACCURATE LOG."
];

export const ACTIVITY_MULTIPLIERS = {
  sedentary: 1.2,
  light: 1.375,
  moderate: 1.55,
  active: 1.725,
  very_active: 1.9
};
