steps:
  - id: 'Build single-service Docker image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'backend/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/power-tracker-one-service', '.']
images:
  - 'gcr.io/$PROJECT_ID/power-tracker-one-service'
